apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-bootstrap
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/navkore/hello-argo.git
    targetRevision: main
    path: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
