apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "redis.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "redis.name" . }}
    spec:
      containers:
      - name: redis
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 6379
        command:
          - "redis-server"
          - "/usr/local/etc/redis/redis.conf"
        volumeMounts:
          - name: redis-config
            mountPath: /usr/local/etc/redis/
      volumes:
        - name: redis-config
          configMap:
            name: {{ include "redis.fullname" . }}
