apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  selector:
    app: {{ include "redis.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 6379
  type: {{ .Values.service.type }}
