apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/navkore/hello-argo.git
    targetRevision: main
    path: apps
    directory:
      include: jenkins-*.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true