apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-argo-helm
  namespace: helm-argo
spec:
  project: default
  source:
    repoURL: https://github.com/navkore/hello-argo.git
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
